### ISSUE TITLE
Smooth Page Scroll draft query

### ISSUE THREAD

**Issue by kimruddock** [pawelgrzybek/pawelgrzybek.github.io#13]
// Prevent requestAnimationFrame from infinte loop
  // In situation is too low on the page
  // And scroll to this position isint possible

I'm not 100% what you're trying to say here. Are you saying you are preventing requestAnimationFrame running when the window has already scrolled beyond the destination point?

**Comment by pawelgrzybek** [comment]
Whenever function scrolls below the document height requestAnimationFrame will create an infinite loop. To prevent you need to first check the window height, whole document height and position of triggered scroll element. If the position is lower than whole documents height, it should scroll to very bottom, without trying to scroll below the document overall height.

Does it make sense man?

**Comment by kimruddock** [comment]
I would suggest changing the comments to:

// Height checks to prevent requestAnimationFrame from infinitely looping
// If the function trys to scroll below the document height
// it should only scroll to the bottom of the document

**Comment by pawelgrzybek** [comment]
Thanks a ton, great idea!

**Comment by kimruddock** [comment]
Also your scroll function includes a call to callback()

if (body.scrollTop === destination) {
      callback();
      return;
    }

but callback() is never defined, should it be?

**Comment by pawelgrzybek** [comment]
Callback is a optional function passed as a one of the arguments.
Have a look here.

Line 82 and 87.
http://codepen.io/pawelgrzybek/pen/QEQoZL

**Comment by pawelgrzybek** [comment]
```js
function scrollIt(element, duration = 200, easing = 'linear', callback) {
  // blah blah blah
}
```

```js
const done = function() {
  console.log('done');
};

btns[0].addEventListener('click', function() {
  scrollIt(sections[0], 300, 'easeInQuad', done);
});
```
