### ISSUE TITLE
Translation - The Observer Pattern in JavaScript explained

### ISSUE THREAD

**Issue by oieduardorabelo** [pawelgrzybek/pawelgrzybek.github.io#38]
Hi @pawelgrzybek,

I've translated one of your articles in my medium:

https://medium.com/@oieduardorabelo/padr%C3%B5es-em-js-observer-pattern-bff0ecc55d01

I added the credits linking to your site and twitter,

What do you think? 💃  Let me know if you want to change something, thanks!

**Comment by pawelgrzybek** [comment]
O wow! Fantastic job! Thank you 🥑
